// AUTO-GENERATED by scripts/build_blog_data.py
// Do not edit manually: rerun model.py then build_blog_data.py
const ATE = {
  "combined": [
    {
      "tour": "ATP",
      "value": 0.0888
    },
    {
      "tour": "WTA",
      "value": 0.055
    }
  ],
  "split": [
    {
      "tour": "ATP",
      "type": "Break Point",
      "value": 0.1362
    },
    {
      "tour": "WTA",
      "type": "Break Point",
      "value": 0.0671
    },
    {
      "tour": "ATP",
      "type": "Tiebreak",
      "value": 0.0072
    },
    {
      "tour": "WTA",
      "type": "Tiebreak",
      "value": 0.0024
    },
    {
      "tour": "ATP",
      "type": "Server Game Point",
      "value": -0.1398
    },
    {
      "tour": "WTA",
      "type": "Server Game Point",
      "value": -0.0581
    }
  ]
};
