// AUTO-GENERATED by scripts/build_blog_data.py
// Do not edit manually: rerun model.py then build_blog_data.py
const ATE = {
  "combined": [
    {
      "tour": "ATP",
      "value": 0.1042
    },
    {
      "tour": "WTA",
      "value": 0.064
    }
  ],
  "split": [
    {
      "tour": "ATP",
      "type": "Break Point",
      "value": 0.147
    },
    {
      "tour": "WTA",
      "type": "Break Point",
      "value": 0.0863
    },
    {
      "tour": "ATP",
      "type": "Tiebreak",
      "value": 0.0267
    },
    {
      "tour": "WTA",
      "type": "Tiebreak",
      "value": -0.0253
    }
  ]
};
