"""
build_blog_data.py
------------------
Reads model outputs (ate_results.csv, feature_importance.csv) and
generates blog_data.js, a JavaScript constants file loaded via script
tag in blog.html, making ATE and feature importance values globally
available to blog.js without any fetch() or CORS risk.

Ensures all D3 chart values are Python-generated and automatically
updated when the model is rerun. No manual hardcoding in the frontend.
"""

import os
import json
import pandas as pd

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR  = os.path.join(BASE_DIR, 'outputs')


# ── Section 1: Defensive File Checks ─────────────────────────────────────────
def verify_inputs(filepaths: list) -> None:
    """Verifies that all required model outputs exist before processing."""
    for path in filepaths:
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"Missing required input: {path}. "
                f"Please run model.py to generate this file."
            )


# ── Section 2: Prepare ATE Data ──────────────────────────────────────────────
def format_ate_data(filepath: str) -> dict:
    """Loads ATE results, asserts data hygiene, and structures for D3."""
    ate = pd.read_csv(filepath)
    assert ate['ATE'].notna().all(), "Unexpected NaNs in ATE results."

    combined = []
    split    = []

    for _, row in ate.iterrows():
        if row['Type'] == 'Combined':
            combined.append({
                'tour':  row['Tour'],
                'value': round(float(row['ATE']), 4)
            })
        else:
            split.append({
                'tour':  row['Tour'],
                'type':  row['Type'],
                'value': round(float(row['ATE']), 4)
            })

    return {'combined': combined, 'split': split}


# ── Section 3: Prepare Feature Importance Data ────────────────────────────────
def format_feature_importance(filepath: str) -> list:
    """Loads feature importance and exports using Pandas native JSON tools."""
    feat_imp = pd.read_csv(filepath)
    assert feat_imp.isna().sum().sum() == 0, "NaNs detected in Feature Importance."
    feat_imp['ATP'] = feat_imp['ATP'].round(4)
    feat_imp['WTA'] = feat_imp['WTA'].round(4)
    return json.loads(feat_imp.to_json(orient='records'))


# ── Section 4: Export to JavaScript ──────────────────────────────────────────
def export_js_constants(ate_dict: dict, feat_data: list,
                        out_path: str) -> None:
    """Writes the formatted data into a static JS constants file."""
    js_content = (
        '// AUTO-GENERATED by scripts/build_blog_data.py\n'
        '// Do not edit manually — rerun model.py then build_blog_data.py\n'
        f'const ATE = {json.dumps(ate_dict, indent=2)};\n'
        f'const featureData = {json.dumps(feat_data, indent=2)};\n'
    )
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(js_content)


# ── Main Execution ────────────────────────────────────────────────────────────
def main() -> None:
    print('=== build_blog_data.py ===')

    ate_path  = os.path.join(OUT_DIR, 'ate_results.csv')
    feat_path = os.path.join(OUT_DIR, 'feature_importance.csv')

    verify_inputs([ate_path, feat_path])

    blog_data    = format_ate_data(ate_path)
    feature_data = format_feature_importance(feat_path)

    out_path = os.path.join(BASE_DIR, 'blog_data.js')
    export_js_constants(blog_data, feature_data, out_path)

    print('  Saved blog_data.js with ATE values:')
    for row in blog_data['combined'] + blog_data['split']:
        print(f'    {row}')
    print('  Feature importance rows:')
    for row in feature_data:
        print(f'    {row}')
    print('=== Done ===')


if __name__ == '__main__':
    main()
