"""
build_blog_data.py
------------------
Reads processed model results and generates blog_data.js —
a JavaScript constants file consumed by blog.js for the D3 reveal chart.

This script ensures the D3 chart values are Python-generated and
automatically updated whenever the model is rerun. No manual hardcoding.
"""

import math
import os
import json
import pandas as pd

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR  = os.path.join(BASE_DIR, 'outputs')


def main():
    print('=== build_blog_data.py ===')

    # Load Python-generated ATE results
    ate = pd.read_csv(os.path.join(OUT_DIR, 'ate_results.csv'))

    # Build structured data for D3 chart
    combined = []
    split    = []

    for _, row in ate.iterrows():
        if row['Type'] == 'Combined':
            combined.append({
                'tour':  row['Tour'],
                'value': round(float(row['ATE']), 4)
            })
        else:
            split.append({
                'tour':  row['Tour'],
                'type':  row['Type'],
                'value': round(float(row['ATE']), 4)
            })

    blog_data = {
        'combined': combined,
        'split':    split
    }

    for entry in combined + split:
        if not math.isfinite(entry['value']):
            raise ValueError(f"Non-finite ATE value detected: {entry}. Rerun model.py.")

    # Write as a JavaScript constants file
    js_content = (
        '// AUTO-GENERATED by scripts/build_blog_data.py\n'
        '// Do not edit manually — rerun model.py then build_blog_data.py\n'
        'const ATE = ' + json.dumps(blog_data, indent=2) + ';\n'
    )

    out_path = os.path.join(BASE_DIR, 'blog_data.js')
    with open(out_path, 'w') as f:
        f.write(js_content)

    print(f'  Saved blog_data.js with ATE values:')
    for row in combined + split:
        print(f'    {row}')
    print('=== Done ===')


if __name__ == '__main__':
    main()
