"""
build_blog_data.py
------------------
Reads ate_results.csv and generates blog_data.js, a JavaScript constants
file loaded via script tag in blog.html, making ATE values globally
available to blog.js without any fetch() or CORS risk.

Ensures all D3 chart values are Python-generated and automatically
updated when the model is rerun. No manual hardcoding in the frontend.
"""

import os
import json
import pandas as pd

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR  = os.path.join(BASE_DIR, 'outputs')


# ── Section 1: Defensive File Checks ─────────────────────────────────────────
def verify_inputs(filepaths: list) -> None:
    """Verifies that all required model outputs exist before processing."""
    for path in filepaths:
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"Missing required input: {path}. "
                f"Please run model.py to generate this file."
            )


# ── Section 2: Prepare ATE Data ──────────────────────────────────────────────
def format_ate_data(filepath: str) -> dict:
    """Loads ATE results, asserts data hygiene, and structures for D3."""
    ate = pd.read_csv(filepath)
    assert ate['ATE'].notna().all(), "Unexpected NaNs in ATE results."

    combined = []
    split    = []

    for _, row in ate.iterrows():
        if row['Type'] == 'Combined':
            combined.append({
                'tour':  row['Tour'],
                'value': round(float(row['ATE']), 4)
            })
        else:
            split.append({
                'tour':  row['Tour'],
                'type':  row['Type'],
                'value': round(float(row['ATE']), 4)
            })

    return {'combined': combined, 'split': split}


# ── Section 3: Export to JavaScript ──────────────────────────────────────────
def export_js_constants(ate_dict: dict, out_path: str) -> None:
    """Writes the formatted data into a static JS constants file."""
    js_content = (
        '// AUTO-GENERATED by scripts/build_blog_data.py\n'
        '// Do not edit manually: rerun model.py then build_blog_data.py\n'
        f'const ATE = {json.dumps(ate_dict, indent=2)};\n'
    )
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(js_content)


# ── Main Execution ────────────────────────────────────────────────────────────
def main() -> None:
    print('=== build_blog_data.py ===')

    ate_path = os.path.join(OUT_DIR, 'ate_results.csv')
    sgp_path = os.path.join(OUT_DIR, 'ate_results_sgp.csv')

    verify_inputs([ate_path, sgp_path])

    blog_data = format_ate_data(ate_path)
    # ate_results_sgp.csv has no 'Combined' row, so every row lands in
    # format_ate_data's 'split' bucket -- append it to the main split list.
    blog_data['split'].extend(format_ate_data(sgp_path)['split'])

    out_path = os.path.join(BASE_DIR, 'blog_data.js')
    export_js_constants(blog_data, out_path)

    print('  Saved blog_data.js with ATE values:')
    for row in blog_data['combined'] + blog_data['split']:
        print(f'    {row}')
    print('=== Done ===')


if __name__ == '__main__':
    main()
